app/blueprints/main/models.py
from app import db, login_manager
from datetime import datetime
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import UserMixin


class User(UserMixin, db.Model):
    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(50), unique=True)
    username = db.Column(db.String(50))
    first_name = db.Column(db.String(50))
    last_name = db.Column(db.String(50))
    password = db.Column(db.String(250))
    date_created = db.Column(db.DateTime, default=datetime.utcnow())
    pets = db.relationship('Pet', backref='user', lazy='dynamic')

    def get_user(self):
        return User.query.get(self.user_id)

    def hash_my_password(self, password):
        self.password = generate_password_hash(password)
    
    def check_my_password(self, password):
        return check_password_hash(self.password, password)

class Pet(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(50))
    type = db.Column(db.String(50))
    description = db.Column(db.String(250))
    image_link = db.Column(db.String(250))
    date_adopted = db.Column(db.DateTime, default=datetime.utcnow())
    owner = db.Column(db.Integer, db.ForeignKey('user.id'))

@login_manager.user_loader
def load_user(user_id):
    return User.query.get(user_id)

app/__init__.py
from flask import Flask, render_template
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
from config import Config
from flask_login import LoginManager

db=SQLAlchemy()
login_manager = LoginManager()

def create_app():
    app = Flask(__name__)
    app.config.from_object(Config)

    migrate = Migrate()
    db.init_app(app)
    migrate.init_app(app, db)
    login_manager.init_app(app)
    
    from app.blueprints.main import bp as main_bp
    app.register_blueprint(main_bp)

    from app.blueprints.auth import bp as auth_bp
    app.register_blueprint(auth_bp)

    from app.blueprints.api import bp as api_bp
    app.register_blueprint(api_bp)
   

    return app

app/blueprints/api/__init__.py
from flask import Blueprint


bp = Blueprint('api', __name__, url_prefix='/api')
from . import routes

app/blueprints/api/routes.py
from flask import jsonify, request, redirect, flash, url_for
from . import bp as app
from app.blueprints.main.models import Pet
from flask_login import current_user
from app import db

# user = current_user.id

app/blueprints/main/__init__.py
from flask import Blueprint

bp = Blueprint('main', __name__, url_prefix='/')

from . import routes, models

app/blueprints/main/routes.py
from flask import render_template, url_for, redirect, request, flash
from app import db
from app.blueprints.auth.forms import PetForm
from . import bp as app
from app.blueprints.main.models import Pet
from flask_login import login_required, current_user



@app.route("/")
def home():

    if not current_user.is_authenticated:
        return redirect(url_for('auth.login'))

    pets = Pet.query.all()
    context = {
        "pets": pets,
        "user": current_user
    }
    return render_template('index.html', **context)

@app.route("/my_pets")
def my_pets():
    pets = Pet.query.all()
    context = {
        "pets": pets,
        "user": current_user
    }
    return render_template('my_pets.html', **context)

@app.route("/adopt/<int:id>", methods=['GET', 'POST'])
def adopt(id):
    owner = None
    form=PetForm()
    pet_to_update = Pet.query.get(id)
    if request.method == "POST":
        pet_to_update.owner = request.form['owner']
        try:
            db.session.commit()
            flash("You have successfully adopted your new pet!")
            return redirect("/")
        except:
            flash("Error.  Try again.")
            return render_template("/adopt.html", form=form, pet_to_update=pet_to_update)

    else:
        return render_template("/adopt.html", form=form, pet_to_update=pet_to_update)

    # if form.validate_on_submit():
    #     owner = form.owner.data
    #     form.owner.data = ''
    return render_template('adopt.html/<int:id>', owner=owner, form=form)

app/templates/adopt.html
{% extends './layout.html' %}
{% block content %}

<h1>Adopt Me</h1>

<div class="container">

    <form action="/adopt/{{ pet_to_update.id }}" method="POST">
        {{ form.csrf_token}}
        <div class="form-group">
            <fieldset id="id-field">
                {{ form.id.label }}
                {{ form.id(class="form-control", value=pet_to_update.id) }}
            </fieldset>
            <fieldset name="name-field">
                {{ form.name.label }}
                {{ form.name(class = "form-control", value=pet_to_update.name) }}
            </fieldset>
            <fieldset type="type-field">
                {{ form.type.label }}
                {{ form.type(class = "form-control", value=pet_to_update.type) }}
            </fieldset>
            <fieldset description="description-field">
                {{ form.description.label }}
                {{ form.description(class = "form-control", value=pet_to_update.description) }}
            </fieldset>
            <fieldset image_link="image_link-field">
                {{ form.image_link.label }}
                {{ form.image_link(class = "form-control", value=pet_to_update.image_link) }}
            </fieldset>
            <fieldset date_adopted="date_adopted-field">
                {{ form.date_adopted.label }}
                {{ form.date_adopted(class = "form-control", value=pet_to_update.date_adopted) }}
            </fieldset>
            <fieldset owner="owner-field">
                {{ form.owner.label }}
                {{ form.owner(class = "form-control", value=current_user.id) }}
            </fieldset>
            <fieldset submit="submit-field">
                {{ form.submit(class = "form-control") }}
            </fieldset>
        </div>
    </form>
</div>


{% for p in pets %}
    {% if p.owner == current_user.id %}
        <div class="card">
            <div class="card-body">
                <div>
                    <p>Name: {{ p.name }}</p>
                    <p>Type: {{ p.type }}</p>
                    <p>Description: {{ p.description }}</p>


                </div>
                <div>
                    <img class="pet-images" src="{{ p.image_link }}">
                </div>
            </div>
        </div>
    {% endif %}
{% endfor %}

{% endblock content %}

app/templates/includes/footer.html
<footer>
    <div class="footer-wrapper">
        
            
        <div class="footer-links">
            <ul class="footer-list">
                <li class="grey-dash">|</li>
                <li><a href="index.html">HOME</a></li>
                <li class="grey-dash">|</li>
                <li><a href="my_pets.html">MY PETS</a></li>
                <li class="grey-dash">|</li>
            
            </ul>
        </div>
    </div>
</footer>

app/templates/includes/header.html
<div class="header-wrapper">
    <nav class="navigation">
        <ul class="nav-links-header">
            <li class="grey-dash">|</li>
            <li><a href="{{ url_for('main.home') }}">HOME</a></li>
            <li class="grey-dash">|</li>
            <li><a href="{{ url_for('main.my_pets') }}">MY PETS</a></li>
            <li class="grey-dash">|</li>
           
            <li class="spacer"></li>
            <!-- <li class="grey-dash">|</li>
            <li class="login-link"><a class="nav-link" href="{{ url_for('auth.login') }}">LOGIN / REGISTER</a></li>
            <li class="grey-dash">|</li> -->


            {% if not current_user.is_authenticated %}
            <li class="grey-dash">|</li>
            <li class="login-link"><a class="nav-link" href="{{ url_for('auth.login') }}">LOGIN / REGISTER</a></li>
            <li class="grey-dash">|</li>
            <!-- <li class="login-link"><a class="nav-link" href="{{ url_for('auth.login') }}">LOGIN</a></li>
            <li class="grey-dash">|</li>
            <li class="register-link"><a class="nav-link" href="{{ url_for('auth.register') }}">REGISTER</a></li>
            <li class="grey-dash">|</li> -->
            {% else %}
            <li class="grey-dash">|</li>
            <li class="logout-link"><a class="nav-link" href="{{ url_for('auth.login') }}">LOGOUT</a></li>
            <li class="grey-dash">|</li>
            {% endif %}
            
        </ul>
    </nav>
</div>

app/templates/index.html
{% extends './layout.html' %}
{% block content %}

<h1>Pet Party</h1>
{% if current_user.is_authenticated %}
<p>Welcome to Pet Party, {{ current_user.username | title }}</p>
{% endif %}


{% for p in pets %}
    {% if p.owner == None %}
        <div class="card">
            <div class="card-body">
                <div>
                    <p>Name: {{ p.name }}</p>
                    <p>Type: {{ p.type }}</p>
                    <p>Description: {{ p.description }}</p>
                    <a href="./adopt/{{ p.id }}">Adopt Me</a>
                        
                </div>
                <div>
                    <img class="pet-images" src="{{ p.image_link }}">
                </div>
            </div>
        </div>
    {% endif %}
{% endfor %}

{% endblock content %}

app/templates/layout.html
<!DOCTYPE html>
<html lang="en">

    <head>
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@300;400;500&display=swap" rel="stylesheet">
        
        <style>
            @import url('https://fonts.googleapis.com/css2?family=Montserrat:wght@300;400;500&display=swap');
        </style>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Pet Party</title>
        <link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
            integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
    </head>

    <body>
        <header>
            {% include './includes/header.html' %}
        </header>

        <main>
            <div class="container">
                {% with messages = get_flashed_messages(with_categories=True) %}
                    {% if messages %}
                        {% for category, message in messages %}
                            <div class="alert alert-{{ category }} alert-dismissable fade show" role="alert">
                                <strong>{{ message }}</strong>
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                        {% endfor %}
                    {% endif %}
                {% endwith %}
            </div>
            {% block content %}
            {% endblock content %}
        </main>
        
        <footer>
            {% include './includes/footer.html' %}
        </footer>
        <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js"
            integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
            crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-fQybjgWLrvvRgtW6bFlB7jaZrFsaBXjsOMm/tB9LTS58ONXgqbR9W8oWht/amnpF"
            crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2"
            crossorigin="anonymous"></script>
    </body>

</html>
    

app/templates/login.html
{% extends './layout.html' %}
{% block content %}
<div class="container">
    <h1>Login</h1>
    <form action="/auth/login" method="POST">
        <div class="form-group">
            <label for="inputEmail">Email address</label>
            <input type="email" class="form-control" name="inputEmail" id="inputEmail" aria-describedby="emailHelp">
        </div>
        <div class="form-group">
            <label for="inputPassword">Password</label>
            <input type="password" class="form-control" name="inputPassword" id="inputPassword">
        </div>
        <p>Don't have an account? <a href="{{ url_for('auth.register') }}">Register Here.</a></p>
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
</div>
{% endblock content %}

app/templates/my_pets.html
{% extends './layout.html' %}
{% block content %}

<h1>{{ current_user.username }}'s Pets</h1>


{% for p in pets %}
{% if p.owner == current_user.id %}
<div class="card">
    <div class="card-body">
        <div>
            <p>Name: {{ p.name }}</p>
            <p>Type: {{ p.type }}</p>
            <p>Description: {{ p.description }}</p>
        

        </div>
        <div>
            <img class="pet-images" src="{{ p.image_link }}">
        </div>
    </div>
</div>
{% endif %}
{% endfor %}



{% endblock content %}

app/templates/register.html
{% extends './layout.html' %}
{% block content %}
<div class="container">
    <h1>Register</h1>

    <form action="/auth/register" method="POST">
        {{ form.csrf_token}}
        <div class="form-group">
            <fieldset id="email-field">
                {{ form.email.label }}
                {{ form.email(class = "form-control", placeholder = "Enter an email address here.") }}
            </fieldset>
            <fieldset id="password-field">
                {{ form.password.label }}
                {{ form.password(class = "form-control", placeholder = "Enter a strong password here.") }}
            </fieldset>
            <fieldset id="confirm_password-field">
                {{ form.confirm_password.label }}
                {{ form.confirm_password(class = "form-control", placeholder = "Re-enter password here.") }}
            </fieldset>
            <fieldset id="username-field">
                {{ form.username.label }}
                {{ form.username(class = "form-control", placeholder = "Enter a username here.") }}
            </fieldset>
            <fieldset id="first_name-field">
                {{ form.first_name.label }}
                {{ form.first_name(class = "form-control", placeholder = "Enter your first name here.") }}
            </fieldset>
            <fieldset id="last_name-field">
                {{ form.last_name.label }}
                {{ form.last_name(class = "form-control", placeholder = "Enter your last name here.") }}
            </fieldset>
            
        </div>
        <p>Already have an account? <a href="{{ url_for('auth.login') }}">Login Here.</a></p>
        {{ form.submit_button(class = "btn btn-primary btn-block") }}
    </form>
</div>


{% endblock content %}